### ISSUE TITLE
Test coverage for setter functions 

### ISSUE THREAD

**Issue by SaberDoTcodeR** [oxydev/SubsCrypt-npm-library#26]
As mentioned [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_3_Noc2.md#general-notes), we should add more test coverage. The tests can not cover the get wallet section but besides that other lines should be covered.
### Current code coverage by Istanbul/nyc
<pre>----------------------------|---------|----------|---------|---------|----------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    
----------------------------|---------|----------|---------|---------|----------------------
<font color="#A2734C"><b>All files                  </b></font> | <font color="#A2734C"><b>  58.78</b></font> | <font color="#C01C28"><b>      25</b></font> | <font color="#C01C28"><b>  48.84</b></font> | <font color="#A2734C"><b>  60.16</b></font> | <font color="#C01C28"><b>                    </b></font> 
<font color="#26A269"><b> src                       </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
<font color="#26A269"><b>  index.js                 </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
<font color="#C01C28"><b> src/polkadot_utils        </b></font> | <font color="#C01C28"><b>  49.06</b></font> | <font color="#C01C28"><b>      25</b></font> | <font color="#C01C28"><b>  48.84</b></font> | <font color="#A2734C"><b>  50.49</b></font> | <font color="#C01C28"><b>                    </b></font> 
<font color="#A2734C"><b>  api.js                   </b></font> | <font color="#A2734C"><b>  51.72</b></font> | <font color="#A2734C"><b>      50</b></font> | <font color="#C01C28"><b>     20</b></font> | <font color="#A2734C"><b>  53.57</b></font> | <font color="#C01C28"><b>11,18-21,25-29,34-36</b></font> 
<font color="#C01C28"><b>  getWalletAccess.js       </b></font> | <font color="#C01C28"><b>  42.86</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#C01C28"><b>      0</b></font> | <font color="#C01C28"><b>  42.86</b></font> | <font color="#C01C28"><b>16-33               </b></font> 
<font color="#A2734C"><b>  interact.js              </b></font> | <font color="#A2734C"><b>  64.71</b></font> | <font color="#C01C28"><b>   33.33</b></font> | <font color="#A2734C"><b>  66.67</b></font> | <font color="#A2734C"><b>  64.71</b></font> | <font color="#C01C28"><b>7,19,26-34          </b></font> 
<font color="#26A269"><b>  subscryptDataGetter.js   </b></font> | <font color="#26A269"><b>  90.91</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>     90</b></font> | <font color="#26A269"><b>  90.91</b></font> | <font color="#C01C28"><b>122-132             </b></font> 
<font color="#C01C28"><b>  subscryptSetFunctions.js </b></font> | <font color="#C01C28"><b>   9.68</b></font> | <font color="#C01C28"><b>       0</b></font> | <font color="#C01C28"><b>      0</b></font> | <font color="#C01C28"><b>  10.34</b></font> | <font color="#C01C28"><b>14-192              </b></font> 
<font color="#26A269"><b> src/polkadot_utils/configs</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
<font color="#26A269"><b>  config.js                </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
<font color="#26A269"><b>  metadata.js              </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
<font color="#26A269"><b>  testConfig.js            </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                    </b></font> 
----------------------------|---------|----------|---------|---------|----------------------
</pre>

**Comment by SaberDoTcodeR** [comment]
### Current code coverage by Istanbul/nyc

File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Lines
----------------------------|---------|----------|---------|---------|-------------------
All files                   |    91.6 |       75 |   88.37 |   92.19 |                   
 src                        |     100 |      100 |     100 |     100 |                   
  index.js                  |     100 |      100 |     100 |     100 |                   
 src/polkadot_utils         |   89.62 |       75 |   88.37 |   90.29 |                   
  api.js                    |   82.76 |       50 |      60 |   85.71 | 11,34-36          
  getWalletAccess.js        |   42.86 |      100 |       0 |   42.86 | 16-33             
  interact.js               |   88.24 |    66.67 |     100 |   88.24 | 7,29              
  subscryptDataGetter.js    |     100 |      100 |     100 |     100 |                   
  subscryptSetFunctions.js  |     100 |      100 |     100 |     100 |                   
 src/polkadot_utils/configs |     100 |      100 |     100 |     100 |                   
  config.js                 |     100 |      100 |     100 |     100 |                   
  metadata.js               |     100 |      100 |     100 |     100 |                   
  testConfig.js             |     100 |      100 |     100 |     100 |                   


subscryptSetFunctions is now 100% tested.  The getWalletAccess can not be tested because they need user interaction with a polkadot{.js} extension.
@Noc2 can you confirm the tests?
https://github.com/w3f/Grant-Milestone-Delivery/pull/250

**Comment by Noc2** [comment]
Yes, I can confirm it. It’s best btw to ping us in our repo, so that the others see your message as well. I’ll be off for a longer period relatively soon. 

<pre>----------------------------|---------|----------|---------|---------|-------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------------|---------|----------|---------|---------|-------------------
<font color="#26A269"><b>All files                  </b></font> | <font color="#26A269"><b>   91.6</b></font> | <font color="#A2734C"><b>      75</b></font> | <font color="#26A269"><b>  88.37</b></font> | <font color="#26A269"><b>  92.19</b></font> | <font color="#C01C28"><b>                 </b></font> 
<font color="#26A269"><b> src                       </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b>  index.js                 </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b> src/polkadot_utils        </b></font> | <font color="#26A269"><b>  89.62</b></font> | <font color="#A2734C"><b>      75</b></font> | <font color="#26A269"><b>  88.37</b></font> | <font color="#26A269"><b>  90.29</b></font> | <font color="#C01C28"><b>                 </b></font> 
<font color="#26A269"><b>  api.js                   </b></font> | <font color="#26A269"><b>  82.76</b></font> | <font color="#A2734C"><b>      50</b></font> | <font color="#A2734C"><b>     60</b></font> | <font color="#26A269"><b>  85.71</b></font> | <font color="#C01C28"><b>11,34-36         </b></font> 
<font color="#C01C28"><b>  getWalletAccess.js       </b></font> | <font color="#C01C28"><b>  42.86</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#C01C28"><b>      0</b></font> | <font color="#C01C28"><b>  42.86</b></font> | <font color="#C01C28"><b>16-33            </b></font> 
<font color="#26A269"><b>  interact.js              </b></font> | <font color="#26A269"><b>  88.24</b></font> | <font color="#A2734C"><b>   66.67</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>  88.24</b></font> | <font color="#C01C28"><b>7,29             </b></font> 
<font color="#26A269"><b>  subscryptDataGetter.js   </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b>  subscryptSetFunctions.js </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b> src/polkadot_utils/configs</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b>  config.js                </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b>  metadata.js              </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
<font color="#26A269"><b>  testConfig.js            </b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>     100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#26A269"><b>    100</b></font> | <font color="#A2734C"><b>                 </b></font> 
----------------------------|---------|----------|---------|---------|-------------------
</pre>
